version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-slack-new"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oxr732qymnfk"
s3_prefix = "sam-slack-new"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=789978052369.dkr.ecr.us-east-1.amazonaws.com/samslacknewc944639c/helloworldfunction19d43fc4repo"]
